version: '3.8'
services:
  auto_backup:
    #  for testing 
    # build: .
    image: minidoracat/auto-backup:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/source:/app/source
      - /path/to/backup:/app/backup
      - ./config.json:/app/config.json
    environment:
      - TZ=Asia/Taipei # 時區
