version: '3.8'
services:
  auto_backup:
    #  for testing 
    # build: .
    image: minidoracat/auto-backup:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/source1:/app/source1
      - /path/to/source2:/app/source2
      - /path/to/backup:/app/backup
      - /path/to/log:/app/log
      - ./config.json:/app/config.json
    environment:
      - TZ=Asia/Taipei # 時區
